project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - gss.qmd
    - newsletter.qmd
    - officers.qmd
    - statistical.qmd
    - university.qmd


website:
  title: "STATS GSA"
  navbar:
    background: primary
    right:
      - gss.qmd
      - newsletter.qmd
      - text: Resources
        menu: 
          - statistical.qmd
          - university.qmd
          - career.qmd
      - icon: github
        href: https://github.com/ucrgradstat/stat_comp

      

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

