---
title: "GSS"
---

The Graduate Students Seminar (GSS) series is an opportunity for graduate students in our department to showcase some of the cool things they are doing, gain presentation practice, and get to know each other. The presentations can be on a variety of topics, including research, projects, internships, a topic you wanted to investigate, a paper that you found interesting, and more. Anything that is appropriate for the graduate-student level audience that could be of interest to the graduate students of this department is welcomed.

The GSS welcomes, and **ENCOURAGES**, anyone who is interested to attend. This includes undergraduates, faculty, and staff. This is open to ALL graduate students. We are hoping to get a variety of topics and perspectives. Please email ucr.grad.stat\@gmail.com your name as soon as possible if you would be willing to put together a presentation, we would be delighted to have you.

# Events

::: panel-tabset
## 2022

### Upcoming Events

#### Estimating Treatment Shift Distributions using eCDFs and Numerical Analysis

Presenter: Jeff Ellis

Date: 5/1/2022

#### Date 5/13/2022

Presenter: Sichen Chen

### Past Events

#### Analysing risk effects of death after aortic valve replacement surgery: a comparison of joint and marginal models

Presenter: Trey McGonigle

Date: 4/15/2022

#### Introduction to Statistical Network Analysis

Presenter: Eric Hayes

Date: 4/8/2022

#### Multivariate Statistical Process Control for Correlated Data in Both Parametric and Non-Parametric Settings

Presenter: Gokul Parakulam

Date: 3/11/2022

#### General State Space Markov Chains

Presenter: Noe Vidales

Date: 2/25/2022

#### Applying to Assistant Professor Positions at the California State University System

Presenter: Isaac Quintanilla Salinas

Date: 2/11/2022

#### Introduction to Python for R Users

Presenter: Rebecca Kurtz-Garcia

Date: 1/28/2022

## 2021

### Introduction to Time Series Analysis

Presenter: Brian Tran

Date: 11/17/2021

### Generalized Additive Models in R using mgcv

Presenter: Jeff Ellis

Date: 11/12/2021

### Outlier Detection for Sparse Functional Data with Cellwise Contamination

Presenter: Xiao Gao

Date: 4/30/2021

### An Introduction to Joint Models of Longitudinal and Time-to-Event Outcomes

Presenter: Debaleena Sain

Date: 4/23/2021

### Parallel Computing with HPCC

Presenter: Isaac Quintanilla Salinas

Date: 3/11/2021

[Presentation](presentations/hpcc_3-11.html)

### Real-Time Classification of Atrial Fibrillation using ECG Characteristics

Presenter: Jericho Lawson

Date: 2/4/2021

### Introduction to Tidyverse

Presenter: Kim Phan

Date: 1/28/2021

[Presentation](PDFS/GSS%20Presenation_About_Tidvyverse.pdf)

## 2020

### SEMI-PARAMETRIC ESTIMATION IN A TWO-COMPONENT LOCATION-SHIFTED MIXTURE MODEL WITH PARTIALLY KNOWN COMPONENT LABELS

Presenter: Bradley Lubich

Date: 12/10/2020

### HOW TO PREPARE FOR DATA SCIENCE INTERNSHIPS: PREREQUISITES, INTERVIEWS AND PROJECTS

Presenter: Jinhui (Jerry) Yang

Date: 11/05/2020

### ASYMMETRIC LOSS FUNCTIONS IN MCMC ESTIMATION

Presenter: Deepak Bastola

Date: 06/02/2020

### THE RCPP PACKAGE: INTEGRATING R AND C++

Presenter: Tyler Brannan

Date: 05/05/2020

### VARYING-COEFFICIENT MODELS

Presenter: Isaac Quintanilla Salinas

Date: 04/21/2020

### A BAYESIAN LONGITUDINAL ANALYSIS OF COUNT DATA WITH GAUSSIAN PROCESSES

Presenter: Samantha VanSchalkwyk

Date: 03/12/2020

### BUILDING SIMULTANEOUS CONFIDENCE BANDS FOR FUNCTIONS

Presenter: Jinhui Yang

Date: 03/05/2020

### JOINT SURVIVAL-LONGITUDINAL MODELING

Presenter: Tyler Brannan

Date: 02/27/2020

### Data Science Internships

Presenter: Dong Ji

Date: 01/30/2020

### Janssen Pharmaceuticals Internships Recap and Joint Modeling of Longitudinal and Time-to-Event Data

Presenter: Luke Klein

Date: 01/16/2020

## 2019

### Divide-and-Conquer for Expectile Regression Processes

Presenter: Zhen Zhang

Date: 12/06/2019

### Identifying the Best Predictive Biomarker in Pharmacogenomics

Presenter: Song Zhai

Date: 11/22/2019

### Bayesian Sensitivity Analysis to Adjust for Unmeasured Confounder in Causal Inference

Presenter: Bibby Zhou

Date: 11/08/2019
:::
